### ISSUE TITLE
Add username/password to the iri requests 

### ISSUE THREAD

**Issue by maeck70** [maeck70/iritop#10]
As it is possible to protect the iri node's access by username/password, this should be an option in starting iritop

**Comment by nuriel77** [comment]
I think this is possible via the URL:

`http://user:password@node-name:1234`

Else, it can be set in the headers.

**Comment by maeck70** [comment]
To put the username/password in the node url will not validate in the regex for the address.
since the password can be complex, I think we still need a way to provide the username password 
separately

**Comment by maeck70** [comment]
Code from Nuriel merged in.
