### ISSUE TITLE
Traceback error when executing from iric

### ISSUE THREAD

**Issue by uwec** [maeck70/iritop#14]
After updating iric to 0.6.9 an executing IRITop out of iric following error message I will see:

![grafik](https://user-images.githubusercontent.com/46627851/51074805-d6b19580-1683-11e9-885d-8fe54d8e49f4.png)

- Installation via PLaybook IRIC (version 0.6.9)
![grafik](https://user-images.githubusercontent.com/46627851/51074838-3019c480-1684-11e9-9576-96e4df79bd47.png)

**Comment by maeck70** [comment]
Any unknown columns for neighbors are now defaulted to 0. This resolves the issue.
This should work correctly in version 0.3.2
