### ISSUE TITLE
During iritop run, removed neighbors break structure

### ISSUE THREAD

**Issue by nuriel77** [maeck70/iritop#25]
While iritop is running, opening a new terminal to add/remove neighbors.

This is an example after having deleted one of the neighbors:

![image](https://user-images.githubusercontent.com/2123208/51215449-442e2200-1921-11e9-9254-e3193409d299.png)

Adding a neighbor seems okay.
However, removing a neighbor that appears on the last line - it doesn't remove from output.

**Comment by maeck70** [comment]
Added cleanup as the order (or count) of neighbors changes.
